function plot_areas( sphynx_id, av, st )

% Get guidata
bregma_ccf = allenCCFbregma;
% gui_data = guidata(probe_atlas_gui);
ap_coords = -((1:size(av,1))-bregma_ccf(1))/100;
dv_coords = (((1:size(av,2))-bregma_ccf(2))/100)*0.85;
ml_coords = -((1:size(av,3))-bregma_ccf(3))/100;

% if ~isempty(plot_structure)
    
    % Get all areas within and below the selected hierarchy level
    plot_structure_id = st.structure_id_path{ sphynx_id };
    plot_ccf_idx = find(...
        cellfun( @( x ) contains( x, plot_structure_id ),...
        st.structure_id_path ) );
    
    % plot the structure
    slice_spacing = 5;
    plot_structure_color = hex2dec(...
        reshape( st.color_hex_triplet{ sphynx_id }, 2, [ ] )' ) ./ 255;
    
    [ curr_ml_grid, curr_ap_grid, curr_dv_grid ] = ndgrid(...
    ml_coords( 1 : slice_spacing : end ),...
    ap_coords( 1 : slice_spacing : end ), ...
    dv_coords( 1 : slice_spacing : end ) );
    
    structure_3d = isosurface(...
        curr_ml_grid, curr_ap_grid, curr_dv_grid,...
        permute( ismember(...
        av( 1 : slice_spacing : end, 1 : slice_spacing : end, 1 : slice_spacing : end ),...
        plot_ccf_idx ), [ 3, 1, 2 ] ), 0 );
    
    structure_alpha = 0.2;
%     gui_data.structure_plot_idx(end+1) = plot_structure;
%     gui_data.handles.structure_patch(end+1) = 
% Set up the atlas axes
axes_atlas = axes( 'ZDir', 'reverse' );
axis( axes_atlas, 'vis3d', 'equal', 'off' ); 
% hold( axes_atlas, 'on' );
    patch( axes_atlas, ...
        'Vertices', structure_3d.vertices, ...
        'Faces', structure_3d.faces, ...
        'FaceColor', plot_structure_color,...
        'EdgeColor', 'none',...
        'FaceAlpha', structure_alpha);
    
% end