%% load allen ccf atlas
allenPath = 'E:\Dropbox (MIT)\Protocols\Histology\AllenCCF';
tv = readNPY( fullfile( allenPath, 'template_volume_10um.npy' ) );
av = readNPY( fullfile( allenPath, 'annotation_volume_10um_by_index.npy' ) );
st = loadStructureTree( fullfile( allenPath, 'structure_tree_safe_2017.csv' ) );

%% Plot brain surface
% (NOTE: non-uniform scaling, DV in CCF is stretched. The DV scaling factor
% has been approximated by comparisons to in vivo MRI images)
bregma_ccf = [ 540, 44, 570 ];
ap_coords = -( ( 1 : size( av, 1 ) ) - bregma_ccf( 1 ) ) / 100;
dv_coords = ( ( ( 1 : size( av, 2 ) ) - bregma_ccf( 2 ) ) / 100 ) * 0.945;
ml_coords = -( ( 1 : size( av, 3 ) ) - bregma_ccf( 3 ) ) / 100;

% Set up axes properties
axes_atlas = axes(...
    'Position', [ -0.3, 0.1, 1.2, 0.8 ],...
    'ZDir', 'reverse' );
axis( axes_atlas,...
    'vis3d', 'equal',...
    'off', 'manual' );
hold( axes_atlas, 'on' );

% Draw brain outline
slice_spacing = 10;
brain_volume = ...
    bwmorph3(...
    bwmorph3(...
    av(...
    1 : slice_spacing : end,...
    1 : slice_spacing : end,...
    1 : slice_spacing : end ) > 1, 'majority' ), 'majority' );

[ curr_ml_grid, curr_ap_grid, curr_dv_grid ] = ndgrid(...
    ml_coords( 1 : slice_spacing : end ),...
    ap_coords( 1 : slice_spacing : end ),...
    dv_coords( 1 : slice_spacing : end ) );

brain_outline_patchdata = reducepatch(...
    isosurface(...
    curr_ml_grid,...
    curr_ap_grid,...
    curr_dv_grid,...
    permute( brain_volume, [ 3, 1, 2 ] ), 0.5 ), 0.1 );

brain_outline = patch(...
    'Vertices', brain_outline_patchdata.vertices,...
    'Faces', brain_outline_patchdata.faces,...
    'FaceColor', [ 0.5, 0.5, 0.5 ],...
    'EdgeColor', 'none',...
    'FaceAlpha', 0.1 );

view( [ 30, 150 ] );
caxis( [ 0 300 ] );
% axis equal

xlim( [ min( ml_coords ), max( ml_coords ) ] )
ylim( [ min( ap_coords ), max( ap_coords ) ] )
zlim( [ min( dv_coords ), max( dv_coords ) ] )

%% Plot selected area
% plot_structure_id = st.structure_id_path{ plot_structure };
% plot_ccf_idx = find( cellfun(@(x) contains( x, plot_structure_id ),...
%     gui_data.st.structure_id_path));
plot_ccf_idx = 701;

% plot the structure
slice_spacing = 5;
plot_structure_color = hex2dec( reshape(...
    st.color_hex_triplet{ plot_ccf_idx }, 2, [ ] )' ) ./ 255;

[ curr_ml_grid, curr_ap_grid, curr_dv_grid ] = ndgrid(...
    ml_coords( 1 : slice_spacing : end ),...
    ap_coords( 1 : slice_spacing : end ),...
    dv_coords( 1 : slice_spacing : end ) );

structure_3d = isosurface(...
    curr_ml_grid,...
    curr_ap_grid,...
    curr_dv_grid,...
    permute( ismember( av(...
    1 : slice_spacing : end,...
    1 : slice_spacing : end,...
    1 : slice_spacing : end ), plot_ccf_idx ), [ 3, 1, 2 ] ), 0 );

structure_alpha = 0.2;
%structure_plot_idx( end + 1) = plot_structure;
% structure_patch( end + 1 ) = patch(...
structure_patch = patch(...
    axes_atlas,...
    'Vertices', structure_3d.vertices, ...
    'Faces', structure_3d.faces, ...
    'FaceColor', plot_structure_color,...
    'EdgeColor', 'none',...
    'FaceAlpha', structure_alpha );
